name: toap
description: "App toDO."

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  #Injeccion de dependencias
  get_it: ^8.0.3

  # Gestor de estados
  flutter_bloc: ^8.1.6

  # Comparacion
  equatable: ^2.0.7
  uuid: ^4.5.1

  # Base de dato local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Otros...
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.13
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  background_color: "#ffffff"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo.png
  uses-material-design: true
